**<h2>--> lab-2 connecting github repo with kaggle and executing some numpy programs</h2>**

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print("a:\n", a)

a:
 [1 2 3]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("b:\n", b)

b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a1 = np.array([1, 2, 3])
print("a1: \n", a1)

print("\nNumber of axes/dimensions in the array: ", a1.ndim)
print("Shape of the array: ", a1.shape)
print("Size of the array/Number of Elements in the: ", a1.size)
print("Type of the elements in the array: ", a1.dtype)
print("Size of the elements in the array: ", a1.itemsize)
print("Buffer containing the array: ", a1.data)

a1: 
 [1 2 3]

Number of axes/dimensions in the array:  1
Shape of the array:  (3,)
Size of the array/Number of Elements in the:  3
Type of the elements in the array:  int64
Size of the elements in the array:  8
Buffer containing the array:  <memory at 0x7ba21b467400>


**<h3>1) creating one dimensions array from list</h3>**

In [5]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


**<h3>2) creating 3x3 matrix that contain values from 2 to 10</h3>**

In [6]:
matrix = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**<h3>3) to append values at the end of an array</h3>**

In [7]:
array = np.array([1,2,3,4,5])
print(array)
array = np.append(array,[6,7,8])
print(array)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]


**<h3>4) to create another shape from an array without changing its data (3x2 to 2x3)</h3>**

In [8]:
matrix = np.array([[2,3,4],[5,6,7]])
print("matrix 2*3 : \n", matrix)
matrix = np.array([[2,3],[4,5],[6,7]])
print("matrix 3*2 : \n", matrix)

matrix 2*3 : 
 [[2 3 4]
 [5 6 7]]
matrix 3*2 : 
 [[2 3]
 [4 5]
 [6 7]]
