In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print("a:\n", a)

a:
 [1 2 3]


In [3]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("b:\n", b)

b:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
a1 = np.array([1, 2, 3])
print("a1: \n", a1)

print("\nNumber of axes/dimensions in the array: ", a1.ndim)
print("Shape of the array: ", a1.shape)
print("Size of the array/Number of Elements in the: ", a1.size)
print("Type of the elements in the array: ", a1.dtype)
print("Size of the elements in the array: ", a1.itemsize)
print("Buffer containing the array: ", a1.data)

a1: 
 [1 2 3]

Number of axes/dimensions in the array:  1
Shape of the array:  (3,)
Size of the array/Number of Elements in the:  3
Type of the elements in the array:  int64
Size of the elements in the array:  8
Buffer containing the array:  <memory at 0x7e79098a7400>
